### PR TITLE
add options support

### PR DESCRIPTION
**Pull request by KyRillosBoshRa**

### CODE REVIEW

**Comment by AhmedKhattab1993** [comment]
I tried sending commands from telegram but they are not getting through to TWS, I tried the basic commands for common stocks

**Comment by KyRillosBoshRa** [comment]
did you enter a valid expiration, strike… etc?

**Comment by AhmedKhattab1993** [comment]
I tied the common stock command that was working before but was not going through I didn't try options

**Comment by KyRillosBoshRa** [comment]
did you change the telegram id?

**Pull request merged**
